# -*- coding: utf-8 -*-
"""matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jShTdUAzJVCDwinTPULX7u45bJTtOoI_
"""

import matplotlib.pyplot as plt
import numpy as np
xpoints = np.array([0, 6])
ypoints = np.array([0, 250])
print(plt.plot(xpoints, ypoints))
print(plt.show())
#Points without line
x= np.array([0, 5])
y=np.array([0, 251])
print(plt.plot(x, y, marker='p'))
print(plt.show())
#Multiple points
xpoints = np.array([1, 2, 6, 8])
ypoints= np.array([3, 8, 1, 10])
print(plt.plot(xpoints, ypoints))
print(plt.show())
#Default X points
ypoints=np.array([3, 8, 1, 10, 5, 71])
print(plt.plot(ypoints))
print(plt.show())

import matplotlib.pyplot as plt
import numpy as np
#Title and label
ypoints = np.array([3, 8, 1, 10, 5, 7])
print(plt.plot(ypoints, linestyle='dashed'))
plt.title("Sample graph")
plt.xlabel('X axis')
plt.ylabel('Y axis')
print(plt.show())
#Marker, Color, Linewidth
ypoints = np.array([3, 8, 1, 10, 5, 71])
print(plt.plot(ypoints, marker = 'o'))
print(plt.show())
xpoints = np.array([0, 6])
ypoints = np.array([0, 250])
print(plt.plot(xpoints, ypoints, "hotpink"))
print(plt.show())
print(plt.plot(xpoints, ypoints, linewidth='20', color='r'))
print(plt.show())
#Multiple lines and grid
y1 = np.array([3, 8, 1, 10])
y2 = np.array([6, 2, 7, 11])
print(plt.plot(y1))
print(plt.plot(y2))
plt.grid()
print(plt.show())
#Sub_plot
#plot 1:
x= np.array([0, 1, 2, 3])
y= np.array([3, 8, 1, 10])
plt.subplot(1, 2, 1)
plt.plot(x,y)
#plot 2:
x= np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])
plt.subplot(1, 2, 2)
plt.plot(x,y)
plt.show()
#Scatter 1
x= np.array([1, 2, 6, 8])
y= np.array([3, 8, 1, 10])
plt.scatter(x, y)
plt.show()
#Scatter 2
x= np.array([1, 2, 6, 8])
y = np.array([3, 8, 1, 10])
plt.scatter(x, y)
a=np.array([5, 7, 9])
b=np.array([2, 5, 8])
plt.scatter(a, b)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])
plt.bar(x,y)
plt.show()
plt.bar([10.25,1.25,2.25,3.25,4.25], [50,40,70,80,20],
label="BMW", width=5)
plt.bar([1.75,1.75,2.75,3.75,4.75],[80,20,20,50,60],
label="Audi", color='r', width=5)
plt.legend()
plt.xlabel('Days')
plt.ylabel('Distance (kms)')
plt.title('Information')
plt.show()
#Horizondal bar
plt.barh(x,y)
plt.show()
#Color option
plt.bar(x,y, color='red')
plt.show()
#Width option
plt.bar(x,y, color='red', width=0.1)
plt.show()
#Histogram
x= np.random.normal(170, 10, 250)
plt.hist(x)
plt.show()
#Pie Chart
у = np.array([35, 25, 25, 15])
plt.pie(y)
plt.show()
#With Labels
у= np.array([35, 25, 25, 15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(y, labels = mylabels)
plt.show()
#Explode
y =np.array([35, 25, 25, 15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode=[10.2, 0, 0, 0]
plt.pie(y,labels=mylabels, explode =myexplode)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.express as px
#Seaborn package
#xpoints = np.array([0, 20, 120,200])
ypoints = np.array([10,80,100,120, 150,180,250])
print(sns.lineplot(data=ypoints))
print(plt.show())
print(sns.scatterplot(data=ypoints))
print(plt.show())
print(sns.barplot(data=ypoints))
print(plt.show())
#3D plot
x= np.array([1, 2, 6, 8, 12, 14, 20])
y = np.array([3, 8, 1, 10, 12, 16, 18])
fig = plt.figure(figsize=(12, 8))
ax = plt.axes(projection="3d")
plt_3d = ax.scatter3D(x, y)
plt.colorbar(plt_3d)
plt.show()
#Plotly package
x=np.array([10,80,100,120, 150,180,250])
fig=px.scatter(x)
fig.show()

